version: '3'

services:
  flask-blog:
    build: .
    container_name: flask-blog
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    restart: always
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production